# Site settings
name: Logan Lemirande
title: Logan Lemirande | Software Engineer
description: I enjoy developing innovative busines solutions through application and web design.
url: http://llemirande.com/
baseurl: "http://lbl28.github.io/"
email: llemirande@yahoo.com
cover: http://llemirande.com/v2/img/og.jpg
logo: http://llemirande.com/v2/img/logo-black.png
resume: http://llemirande.com/resume.pdf
social:
  - title: email
    url: mailto:llemirande@yahoo.com
  - title: twitter
    url: https://twitter.com/llemirande
  - title: instagram
    url: https://instagram.com/llemirande
  - title: github
    url: https://github.com/lbl28
  - title: linkedin
    url: https://www.linkedin.com/in/llemirande

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
